services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  media-hooks:
    environment:
      - WHISPER_DEVICE=cuda
      - WHISPER_COMPUTE_TYPE=int8_float16
