import { SectionHeader } from "./section-header"
import type { IntelligenceReportData } from "./types"

export function AnalystNotes({ data }: { data: IntelligenceReportData }) {
  return (
    <section className="px-8 py-4">
      <SectionHeader number={5} title="ANALYST NOTES" />
      <div className="pl-5 font-serif text-sm italic leading-relaxed text-ink/70">
        <p className="mb-3 not-italic font-semibold text-ink/80">
          AI ANALYST ASSESSMENT (ADVISORY):
        </p>
        {data.analystNotes.map((paragraph, idx) => (
          <p key={`${idx}-${paragraph.slice(0, 24)}`} className={idx > 0 ? "mt-3" : ""}>
            {paragraph}
          </p>
        ))}

        <p className="mt-4 text-[11px] not-italic text-ink/40">
          NOTE: This assessment is generated by the OSINT NEXUS AI analytical engine and
          should be reviewed by a qualified human analyst before incorporation into
          operational planning or decision-making processes.
        </p>
      </div>
    </section>
  )
}
